# Numpy Assignment

In [ ]:
# 1. What is a Python library? Why do we use Python libraries?

""" A Python library is a collection of modules and functions that extend the capabilities of the Python 
programming language. These libraries provide pre-written code to perform specific tasks, making it easier for 
developers to implement functionalities without having to start from scratch. Python libraries cover a wide range 
of domains, including mathematics, data analysis, machine learning, web development, networking, and more."""

In [ ]:
# 2. What is the difference between Numpy array and List?

"""
1. Performance: NumPy arrays are more efficient for numerical operations than lists. NumPy is optimized for 
array operations, which are implemented in C, resulting in faster execution compared to the more general-purpose 
Python lists.

2. Homogeneity: NumPy arrays have a fixed data type for all elements, ensuring homogeneity. In contrast, Python
lists can contain elements of different data types.

3. Memory Consumption: NumPy arrays generally consume less memory than lists. NumPy uses a contiguous block of 
memory, whereas lists are more flexible, leading to higher memory overhead.

4. Ease of Use: NumPy provides a variety of built-in functions and operations specifically designed for array 
manipulation. This makes it easier and more convenient to perform mathematical and logical operations on NumPy 
arrays compared to lists.

5. Functionality: NumPy arrays support vectorized operations, broadcasting, and other advanced mathematical 
functions, making them suitable for numerical computing. Lists, being more general-purpose, lack these specialized 
functionalities.
""""""

In [1]:
# 3.Find the shape, size and dimension of the following array? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

import numpy as np
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Shape
shape_of_array = my_array.shape
print("Shape of the array:", shape_of_array)

# Size
size_of_array = my_array.size
print("Size of the array:", size_of_array)

# Dimension
dimension_of_array = my_array.ndim
print("Dimension of the array:", dimension_of_array)

Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


In [2]:
# 4. Write python code to access the first row of the following array? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


first_row = my_array[0, :]
print("First row of the array:", first_row)

First row of the array: [1 2 3 4]


In [3]:
# 5. How do you access the element at the third row and fourth column from the given numpy array? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

element = my_array[2, 3]
print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [4]:
# 6. Write code to extract all odd-indexed elements from the given numpy array? [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

odd_indexed_elements = my_array[:, 1::2]

print("Odd-indexed elements from the array:")
print(odd_indexed_elements.flatten())

Odd-indexed elements from the array:
[ 2  4  6  8 10 12]


In [ ]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)

In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?

"""
1. Distribution Type:
   - `np.random.rand`: Generates random values from a uniform distribution over the range [0, 1).
   - `np.random.randn`: Generates random values from a standard normal distribution (mean = 0, standard deviation = 1).

2. Arguments and Shape:
   - `np.random.rand`: Accepts separate arguments for each dimension and generates values in the [0, 1) range. For example, `rand(3, 4)` generates a 3x4 matrix.
   - `np.random.randn`: Takes a variable number of arguments for each dimension but generates values from the standard normal distribution. For example, `randn(3, 4)` generates a 3x4 matrix.

3. Uniform vs. Normal Distribution:
   - `np.random.rand`: Produces values uniformly distributed between 0 and 1, with each value having an equal chance of being selected.
   - `np.random.randn`: Generates values from a normal (Gaussian) distribution, where values are more likely to be near the mean (0) and less likely as they move away.

4. Parameterization:
   - `np.random.rand`: Does not require parameters for mean and standard deviation since it generates values in a fixed range.
   - `np.random.randn`: Can take optional parameters for mean and standard deviation to customize the distribution. The default is a standard normal distribution.

5. Use Cases:
   - `np.random.rand`: Useful when you need random values with a uniform distribution, for example, when initializing weights in neural networks or creating random matrices for certain simulations.
   - `np.random.randn`: Useful when you specifically need random values following a standard normal distribution, commonly used in statistical modeling and simulations.
"""

In [5]:
# 9. Write code to increase the dimension of the following array? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

new_dimension_array = np.expand_dims(my_array, axis=2)

print("Original array shape:", my_array.shape)
print("Array with increased dimension shape:", new_dimension_array.shape)
print(new_dimension_array)

Original array shape: (3, 4)
Array with increased dimension shape: (3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [6]:
# 10. How to transpose the following array in NumPy? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

transposed_array = my_array.T

print("Original array:")
print(my_array)
print("\nTransposed array:")
print(transposed_array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [7]:
"""  11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python: 
1. Index wise multiplicatio'
2. Matrix multiplicatio'
3. Add both the matricK
4. Subtract matrix B from  
5. Divide Matrix B by A   """

matrix_A = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

matrix_B = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = matrix_A * matrix_B

# Matrix multiplication
matrix_multiplication = matrix_A @ matrix_B.T  # Used Transpose of B for proper multiplication

# Addition
matrix_addition = matrix_A + matrix_B

# Subtraction
matrix_subtraction = matrix_A - matrix_B

# Element-wise division (using np.divide)
matrix_division = matrix_B / matrix_A

# Displaying results
print("Index-wise Multiplication:")
print(index_wise_multiplication)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

print("\nMatrix Addition:")
print(matrix_addition)

print("\nMatrix Subtraction:")
print(matrix_subtraction)

print("\nMatrix Division:")
print(matrix_division)


Index-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix Division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

""" In NumPy, the function numpy.ndarray.byteswap can be used to swap the byte order of an array. This function is 
applied to a NumPy array, and it swaps the byte order of the array elements in place. """


original_array = np.array([1, 2, 3, 4], dtype=np.int32)

swapped_array = original_array.byteswap()

print("Original Array:")
print(original_array)
print("\nSwapped Array:")
print(swapped_array)

Original Array:
[1 2 3 4]

Swapped Array:
[16777216 33554432 50331648 67108864]


In [ ]:
# 13. What is the significance of the np.linalg.inv function?

"""
1. Matrix Inversion:
   - `np.linalg.inv` calculates the inverse of a square matrix, which is a matrix that, when multiplied by the 
   original matrix, results in the identity matrix.

2. Solution to Linear Systems:
   - Matrix inversion is often used to solve systems of linear equations. If \(Ax = B\), where \(A\) is a matrix 
   of coefficients, \(x\) is the vector of variables, and \(B\) is the vector of constants, then \(x = A^{-1}B\).

3. Numerical Stability:
   - While matrix inversion is a powerful tool, it may not always be numerically stable, especially for 
   ill-conditioned matrices. It's important to be cautious when using the inverse, and alternative methods like 
   solving linear systems directly may be preferred in some cases.

4. Applications in Statistics and Optimization:
   - In statistics, the inverse of a matrix is used in multivariate analysis, such as calculating the covariance 
   matrix or estimating regression coefficients. In optimization, the inverse can be employed in solving least 
   squares problems.

5. Eigenvalue and Eigenvector Calculations:
   - The inverse of a matrix is also related to eigenvalues and eigenvectors. In particular, if \(A\) is a matrix
   with eigenvalues \(\lambda_1, \lambda_2, \ldots, \lambda_n\), and eigenvectors \(v_1, v_2, \ldots, v_n\), then 
   the inverse of \(A\) has eigenvalues \(1/\lambda_1, 1/\lambda_2, \ldots, 1/\lambda_n\) and 
   eigenvectors \(v_1, v_2, \ldots, v_n\).
"""

In [ ]:
# 14. What does the np.reshape function do, and how is it used?

"""
The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a 
new array with a modified shape, and the original array remains unchanged. The function takes the original array 
and the desired new shape as arguments.

Functionality: np.reshape rearranges the elements of the input array to fit into the specified shape. It doesn't 
alter the data; it merely provides a different view of the same data in a new shape.

Syntax: 

np.reshape(a, newshape, order='C')
a: The array to be reshaped.
newshape: The new shape specified as a tuple of integers or a single integer.
order: Optional parameter specifying the order in which the elements are read during reshaping. It can be 'C' for 
row-major (default) or 'F' for column-major.
"""

In [ ]:
# 15. What is broadcasting in Numpy?

""" Broadcasting in NumPy is a mechanism that enables the performance of element-wise operations on arrays of 
different shapes without the need for explicit looping. It automatically extends smaller arrays to match the shape 
of larger arrays, following rules that compare dimensions element-wise. This eliminates the need for manual 
alignment or reshaping, making code more concise and readable. Broadcasting is memory-efficient, as it operates on 
the original arrays without creating unnecessary copies. It plays a crucial role in NumPy's ability to perform 
efficient array operations on arrays with varying shapes, enhancing the simplicity and expressiveness of array 
computations."""